[build]
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://storeserver-production-bc7e.up.railway.app/api/v1"
  status = 200
  force = true

[[build.environment]]
  name = "VITE_STRIPE_PUBLIC_KEY"
  value = "pk_test_51MNXIVSA8sRIIEU2royAMOd0yeSoWAgHTEPjr0o8xGAeBFADb56uhTI6XO92TDWskCraXe2oe6vTYOZMYjJ6GicN002zi0la1g"

[[build.environment]]
  name = "VITE_STRIPE_SECRET_KEY"
  value = "sk_test_51MNXIVSA8sRIIEU2cAfFqEegfyNQiUqc6IBVcQd164WaONwOczeN1D9SQYyNKs00841nOSTVZaVLGYWPXkL8pE6A00zRhRSGjR"